#               _
#    ___  _ __ (_)  ___   ___   _ __   _ __
#   / _ \| '__|| | / __| / _ \ | '_ \ | '__|
#  |  __/| |   | || (__ | (_) || | | || |
#   \___||_|   |_| \___| \___/ |_| |_||_|
#

add_newline = false

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$env_var\
$crystal\
$cmd_duration\
$custom\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

[character]
format = "$symbol "
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[git_branch]
symbol = ""

[git_status]
modified_count.enabled = true
modified_count.style = "green"
staged_count.enabled = true
show_sync_count = true

[package]
style="bright-green"

[golang]
symbol="Go "
style="bold yellow"

[rust]
symbol="Rust "
style="bold red"

[line_break]
disabled = true
